### ISSUE TITLE
Another Youtube Tuitorial Link for Beginner by Yogita Sharma

### ISSUE THREAD

**Issue by ProPhycient5** [ashishps1/awesome-system-design-resources#13]
[sudoCode](https://www.youtube.com/@sudocode) by [Yogita Sharma](https://www.linkedin.com/in/yogita-sharma-83400b55/?originalSubdomain=ae) is also go-to tutorials for pure newbies in System Design irrespective of their FE or BE domain.

@ashishps1, please check if you find useful, then add to the list Tutorial Section.

**Comment by ashishps1** [comment]
Hey, I have added it.

Closing it now.

**Comment by ProPhycient5** [comment]
Sure @ashishps1. Thanks 🙏
