### ISSUE TITLE
The link to Service Discovery is broken

### ISSUE THREAD

**Issue by ksid49** [ashishps1/awesome-system-design-resources#14]
To me this link - https://www.f5.com/company/blog/nginx/service-discovery-in-a-microservices-architecture shows as Not found on Mobile and on laptop opens a filter results which is clearly not a blog.

**Comment by ashishps1** [comment]
hey, seems this link no longer exists.

I have updated the service discovery url link: https://newsletter.ashishps.com/p/0204da93-f0e9-49b9-a88a-cb20b9931575

Closing this issue.
